name: Shell Commands
on: [push]
jobs:
  run-commands-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-commands-on-windows:
    runs-on: windows-latest
    needs: ["run-commands-on-ubuntu"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
